controllers:
    resource: ../../src/Controller/
    type: annotation

user_ui:
    resource: ../../src/Common/Infrastructure/UI
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
